### PR TITLE
Upgrade java agent to 3.15.0

### PR DESCRIPTION
**Pull request by mausch**

### CODE REVIEW

**Comment by amonje** [comment]
I'd recommend using "current" for java agent version, and downloading *.jar. will always grab latest...

ex:
2.2.0 :001 > require 'open-uri'
 => true
2.2.0 :002 > url_content = open('https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/') {|f| f.read.lines.grep(/jar/i).to_s }
 => "[\"<a href=\\\"newrelic-agent-3.15.0.jar\\\">newrelic-agent-3.15.0.jar</a>                          31-Mar-2015 18:22             7064901\\r\\n\"]"
2.2.0 :003 > name = url_content.split(/\W+jar/).first.to_s.split("\\\"").last + '.jar'
 => "newrelic-agent-3.15.0.jar"
2.2.0 :004 >

**Comment by mausch** [comment]
I'd rather keep the recipe as deterministic as possible, even if the consumer doesn't define a particular agent version.

**Comment by ge1st** [comment]
@mausch I don't agree. I'd agree if the cookbook was more opinionated but this cookbook is being used by many in a very generic way and is being wrapped up to define a specific version. In fact, we're forced to wrap it because this cookbook consistently runs behind the `current`. 

If you look at other community cookbooks, like say Java, it does pull the latest, at least for a major. I don't feel it's the task of a cookbook like this to define a version, that's the responsibility of the people using it. It's also less work for the maintainers and probably for you, since you don't have to submit/wait on a PR every time you want a version bump.

**Comment by djoos** [comment]
Hi guys,

thanks for this thread. We're making some changes to the agent recipes (introduction of LWRPs) and I'm keen on getting a solution that allows you to have ['newrelic']['java_agent']['version'] set to 'latest' (=new default value for attribute), in which case some logic based upon @amonje's suggestion will be used to get the latest/current version and otherwise grab a particular version, which is how it works right now.

This way the cookbook will be able to grab latest by default, but you can still be more deterministic if your setup requires so. FYI: I'll reference the PR/commit once it goes out.

Hope this helps!

Kind regards,
David

**Pull request closed without merging**
