### PR TITLE
added ability to add extra additional config

### PR DESCRIPTION
**Pull request by willejs**
We need to add some undocumented config to fix an error. Generally, it's nice to be able to add additional config if needed when you dont want to make a pr to the cookbook as its edge case, or not needed by everyone.

### CODE REVIEW

**Comment by willejs** [comment]
@djoos does this look good to you?

**Comment by djoos** [comment]
Looks good to me - I'll try to get this merged in later this week!

**Comment by djoos** [comment]
Thanks for your contribution @willejs!

Kind regards,
David

**Comment by willejs** [comment]
Thanks @djoos !

**Pull request merged**
